namespace CSharpHistorySamples.V09;

internal static partial class V9
{
    internal static void Records()
    {
        WriteFirstLineInSample("Records");
        var derivedRecord = new DerivedRecord(1, 2);
        var derivedRecord2 = new DerivedRecord2(1, 2);
        BaseRecord baseRecord = derivedRecord;

        // baseRecord.X = 2; cannot be mutated


        WriteLine($"Are base and derived same references: {ReferenceEquals(baseRecord, derivedRecord)}");


        WriteLine($"Nondestructive mutation:");
        // new object can be created as a copy with optionally updated props
        var updatedRecord = baseRecord with
        {
            X = 1
        };

        WriteLine($"Type of updated record: {updatedRecord.GetType()}");
        WriteLine($"Are base and updated same references: {ReferenceEquals(baseRecord, updatedRecord)}");
        WriteLine($"Hash codes; derived: {derivedRecord.GetHashCode()} base: {baseRecord.GetHashCode()} updated: {updatedRecord.GetHashCode()}");
        WriteLine($"Are equal base and updated: {baseRecord.Equals(updatedRecord)}");
        WriteLine($"Are equal derived and updated: {derivedRecord.Equals(updatedRecord)}");

        WriteLine($"Are equal derived and derived 2: {derivedRecord.Equals(derivedRecord2)}");
        WriteLine($"Hash codes; derived: {derivedRecord.GetHashCode()} derived2: {derivedRecord2.GetHashCode()}");

        WriteLine($"Auto generated formatted ToString: {derivedRecord}");

        var record2 = new RecordWithParameterlessConstructor()
        {
            X = 1,
            Y = 2,
        };

        var record3 = record2;
        WriteLine($"Are same objects after assignment: {ReferenceEquals(record3, record2)}");
    }

    internal abstract record BaseRecord(int X); // can be abstract

    internal record DerivedRecord(int X, int Y) : BaseRecord(X)
    {
        protected DerivedRecord(DerivedRecord other)
            : base(other)
        {
            Y = other.Y;
            WriteLine("Copy constructor called");
        }

        // CS8859 Members named 'Clone' are disallowed in records - they are autogenerated by the compiler
        //protected DerivedRecord Clone() { }
    }

    internal record DerivedRecord2(int X, int Y) : BaseRecord(X);

    internal record RecordWithParameterlessConstructor()
    {
        internal int X { get; init; }
        internal int Y { get; init; }
    }

    // cannot inherit from classes:
    // internal class SomeClass();
    // internal record DerivedFromClassRecord() : SomeClass;
}
